### PR TITLE
Copy api-outline.md content to Bikeshed document

### PR DESCRIPTION
**Pull request by Orphis**
This is just a bare skeleton to be filled later.

***
<a href="https://pr-preview.s3.amazonaws.com/Orphis/webrtc-rtptransport/pull/73.html" title="Last updated on Sep 25, 2024, 1:44 AM UTC (29389db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webrtc-rtptransport/73/92b1d76...Orphis:29389db.html" title="Last updated on Sep 25, 2024, 1:44 AM UTC (29389db)">Diff</a>

### CODE REVIEW

**Comment by aboba** [comment]
@orphis Can you fix the issue and merge this?

**Review by aboba — CHANGES_REQUESTED** [review]
Still showing an error: 
 Element “dl” is missing a required instance of child element “dd”.

**Comment by Orphis** [comment]
It shows a line number in the generated file and not in the source file, it doesn't help much. 🫤

**Comment by aboba** [comment]
@orphis There was a missing </dt> at line 835.

**Comment by Orphis** [comment]
Also found it, it also needs a `<dd>` block for each `<dt>`.

**Comment by Orphis** [comment]
Changed `readonly sequence<X> foo;` to `sequence<X> getFoo();` to make the IDL validation happier.
Marked everything available in Window too, we can update that when we merge the other PRs dealing with Worker transfers.

**Comment by aboba** [comment]
@orphis Should we make the argument optional?

**Comment by Orphis** [comment]
I hope it will be fine since one of the overloads takes an interface and the other one a dict. So when we use the optionality of the 2nd argument, they'll look very similar (but one will return a Promise). We can address that later if it's an issue.

**Comment by aboba** [comment]
Yeah!

**Pull request merged**
